replicaCount: 3
namespace: prod-ns

image:
  repository: aravindroy1/washify-auth
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization: 80

configMap:
  name: auth-config

secret:
  name: auth-secret
  jwtSecretGibberish: "AgBeaoMyf0MVOQhPtMOQq07U4vZ3T4kVMt5eCPV3mrgOMRKnUSdhYWmomaqpzOusCs+TXLWW9NOEcIb+TB61zgCySdMuWBNioPif5zI6GmZGj2jDNlLZNc8QVyE/rnpNywWZAX45gW6e5BKQohflFc89Vb5rzH1LoyLgJl9Ju7uGBD8o75NcA1EsCjpdTw81tVrPBYM/RO7f88g07wEznm8z6W1E8NYt2R2CsUaAmdGDvPjw8l0ITPnYdHuFdYTdLgm9BfKVUWCscYBfE0OnkYwtTdDa3WijxBMhrhawdgMlouuE2U2JHeY5cFkj5AJJ4Kdv/sydQ4Cd5M0eUw0japbCUKnL5kN9apL+eL4GJVLh5wFQ9cMkiDOAQRv7q/W2PITZQv3s3h4z2Q/u3gFsRZLCh0WGrOyolTqVoS0Fq5PqI9YAqYcd0KLgawm1lgNhRIugcT564sO8d/1oYCk58mW8bzbF3ub3jmlKAnWHx7ezuEpzerkzHbHF1J2LTRMuuQ+mCbh8Dz17i0Wi/VusvJ7gPDenk77Sj/gqBYwwAuTpe0XppQAKlzH9Wy5OoZRvbqaBonHcEBA98rFV/dfmHJpUsDbRteBZtzL/qiYxbDkAmuyX2KcI+OVrV/QmwdSxT2k8wdXXEWfpM0XFjjNiRvxJbWeQK0LBSUX4n1OS58S92CRVhUvNA15F/nZYNlQQL8iQfYTtaihM3S8snuPHaKQ="


config:
  mongoUrl: "mongodb://mongodb:27017"

livenessProbe:
  path: /docs
  port: 8000
  initialDelaySeconds: 15
  periodSeconds: 20
