replicaCount: 3
namespace: prod-ns

image:
  repository: aravindroy1/washify-auth
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization: 80

configMap:
  name: auth-config

secret:
  name: auth-secret
  jwtSecret: "prod-secret-key"

config:
  mongoUrl: "mongodb://mongodb:27017"

livenessProbe:
  path: /docs
  port: 8000
  initialDelaySeconds: 15
  periodSeconds: 20
