replicaCount: 1
namespace: dev-ns

image:
  repository: aravindroy1/washify-auth
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000
  targetPort: 8001

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization: 80

configMap:
  name: auth-config

secret:
  name: auth-secret
  jwtSecret: "AgAQwY/v49K8Qqg4m8dZvfQqzkIMBRtrhuhIH+Yobud3AgoJPYPC62pg9tKnzgJRDdDZfFHa8QBkQkPlqODtLCeEDn7zMoFUmN5fMYRoopi+FRWaoz76SM4FukZSWtG6E0QtVgxYa99T96z60pCutsKXa587c0Vbl2cy8f9TM/D2hjKg0fhx2vky7ytD0FO4H6T4jkj+U2mHXGG2R7xi2rAHruTECblgwUlllyWSjNTpfoup7w4dWPHkxDdfnuGt1hdaqOhRC+iodH3poKnIcjd9JYc4xAUNzflMxi8aNnXP9I1gxUHfa4AF0Xtk0TZRG3m/zVJmIdTRdM788ggAwln38wuPCjEum/aYPKjFFvAxZxqC9Z59Ng0s/iP5JNOg6A1F1pZp7vfYVDVDLLTT4s3B8t6/bHBr458Icu7RYV6uRw+0WAX3ifmtiM6Csix2nPOZZ06aAcUN6Bh1P9K+PEjvqRCq4BuUkbUNMvjf3ykvTYIYbB3IKi10nGJ+w3F6VAn/Ck7SR4EMPp1x/TfVOWfUdB7KWMzL6RMyFhkanc1pnerZmEVE0XIGh8PKqigLIZvn8V5SjpE/FX4diCbqncL/SvWnU8xwBQF/Kj/jFxHSmub0YIIlaOpAafVr+QOb1iUWGTl22Ce58IjJsr5YTjfWjK6kyhFjSL3vCkx2jb+IcDXaLHyDh58mGdvYhsNor8sp6sQKRwmiQXubbzn5vg=="

config:
  mongoUrl: "mongodb://mongodb:27017"

livenessProbe:
  path: /docs
  port: 8001
  initialDelaySeconds: 10
  periodSeconds: 15
