apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/WashifyApp/washify-gitops.git
    targetRevision: main
    path: charts/frontend
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: argoproj.io
    kind: Rollout
    jsonPointers:
    - /spec/replicas
    - /status
  - group: autoscaling
    kind: HorizontalPodAutoscaler
    jsonPointers:
    - /spec/maxReplicas
