apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/WashifyApp/washify-gitops.git'
    targetRevision: main
    path: environments/prod/infra
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
