replicaCount: 3
namespace: prod-ns

image:
  repository: aravindroy1/washify-notification
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization: 80

configMap:
  name: notification-config

secret:
  name: notification-secret
  jwtSecretGibberish: "AgCpysf7eZ+Yat9lgB7ChPJZfFi4H3P3hW/vLjJ2dCyjltTCxdpsgHTmrmel0ujo93jIWLRNHe97/KjcsWvV7DFYr4x71+cYkq6g9OOnXBaAHi5GI1K3RWBS4m7XLIRsstQjg8TEWdjxn1/aUFwtVRa1K8+Lqeiw/P+X9qJg3FYaZvrPqNYocpbydZROAG00MKkRtKKm8QwGmJ1w2usv+bLrt7+pmoCrmibk405eTpDiaYdWRXX32CTFWaIheuQSiCsWrSoky3HdeCMvrZ1qNGL8ZiO/1q2Siw91NFuiOdDLxXP643Dk7pzi6l1zkoO0pDdan5EztYR6n/F1ra95fwS2IwuD08GzrOhlUTnMr5nytKZIdY44c0d65Oq7kR/uLnxrM0RBVVsYEPOnJEz7+9+Po6XuKwlIdyP5gZBhHI97mDElQ8w0tnaqnfvlEbmn5RehB5zZt0xCioTR5oSIZczZTSHP8nIm3NIIvuFUbbggEGKmk1+0C2JBZ+VSW3eO7B3yn3NRcuGfeYI7jVv2TMDwVPsNHIUyKxtAbMgpjysKjdr/Xh9H9gwcZeI7xfmZEHL7vMEkl73q+LoOFlcMY96ZRSBXJ1THNjgPAB8Zj2/ZsN4/JOR6IHvyeKBE/rg423w6mN9gqr40rQCdESXSeXvCGuTUVa+d6RroVmgayzvqpZSDHe83+0WItC7LlHDrziiugoepyAlQ+IxLlSQPr9g="
  smtpUserGibberish: "AgA8hMHhcKuoNXuoxzD/1POJYnp3aV+6O87ZRBmlRNOnAqhi9RzMYzW3VfCn1ityxX9k2zriqpSw0GE1vMU3jp5Gl3bOMn8X8PKs44n2DkktMw2+EyAjtG3gspHmRvHvVAuv9orI96DhPinZAjf6VRDkemMzGrUG+8ql7GK0vNa4yfpNKQbgIwiCbf1oELdY69UGVsKCyJiUYN2gXedEmvPeYkj5rYaxqzIy14r4bsSl2EYKgwuT/VxTnuIjjEFi5Fp3ZSVasam0U0k8vfkfRTRakVab4+qzNJMpSeod3/Ps7WTkMQtigFJf58nQyZWp82iHGGs8rNQWcfnBNG1Bj1OwqyeMnk5L4GsCMgcYy+XySmTvz4i6Hbl5w04RSkC9kmL/VY9AORKcfo8GvsPWvVp2JZPFeAab/PFekwJBbE1HiquYbE7WNwNMRvJE/MhLJ1GPwFjKC50C6DUk4lo9cfnAqwl3bkzmBuvKDqhgrV2g2KDo87+xEzn11zcdMTEFi8465JnF91paNEiMRbSBSfRbtKOn1Paf6lPl7dUuScxTzi28W8s87V0CB2r51O/IS+HbFW5Vhm1F/5derZGIKMX5VDlgnF7KTjslrZNAUias6/y+CQ4R8QJo/bMD3kYsdQrrtJnyorFLZTKi8CWU5YO2z9Nom9aWf9D698DrNczE1P1s0jDmbmEVyDfmmE1Ps3O73u7YAbyDdcT3JMqM/M1UA9eC9g=="
  smtpPassGibberish: "AgAKiU1MNipz3V8Gs5NST/zAkk1fmDhA6BrO5tSsNkFdgMPATkJtvsz4SFHg2wRP44KDgSKIL00V4SwSQAxFq9/nlESK69nklL1vscrRvM19Ps8Hnll4qF8c7/KcRJZzNxZwpXCWC5FAWLF95+qkWuI1+g3euX3co7lSaIg+xYxsberwIpaWXIWXZgotz9KkCmDTy2cUVUDvKvh+PqtmT0SZzVdEhXp0CAg/5Ia6/i6hEwgL73HMR5TqLAGExfYI0HacH+PXFSwOZv02MxkiXTYkparbsrVDdRt7XoFB+hh+/bKVF/ohHTuCiSxEWK0FLpU3PmbagU325alaYoNZO4U4WEqTf7RkQOsjyVNgU8ukEQQNHBOCaVmwA/xdGEBPm8T5EnVcYhiSmIwpHG6mqQUBXVSYN6vyvjA9gl8uQzOw7FT/BvAAWfY56fVRq9p4WzPHF8/MptqptuyvECdSL4fgfDYoiN1WCpDjJrZhI2lYpcCcNpburmYRI8oHR0/Vh/dRDJWHl5EcEwYhUnHPRDpaKhklNKk/bpJEQFM0Op6OT3ax0TWAPXc6FY8AG+8ohaaRDhxQ24Zni8xDopBa2XYIe3ptbSPZJHAZQ5gaN+ZXwVkdYVBqYyF8Un1uDFsU4sSgRt6aAH3nkIyZ65RzvWZf61dEQwqwe4FkYymHaXKXFN7y/bK5KwIhadqZ/rHWPWvAkJ57FZQTmvRQBs1FjS4n"
  twilitwilioSidGibberishoSid: "AgAKiY11CMOO4TLYrgh24kMUb3v/8c7ZI52SGap93657o2Du1VIlazeGzdUJYffwoDYPWRs5rAZCufDyFwwaGwMZ0ArBmyurPF0U+s6YzK+W5tqQ7UWOkRJB0fQjawFr88fGMs89oY7/Y6FCVynODksx8pqD4TymNGrXRGZ7WgGOY5UT5fjP5h/MwInv85jKLwVFD0np2rR8d68ADLKfXRm6qenSUMl9StRCrR4809Z21bn1qIonPyPT8Az3NF+OJUQ88kESK9TzF+EQR+T08bJWyOWDfimiQtqDadBy+Eww9K5CkGf9wLflslgCjbSlM9BmvauHbeCpfyZO7VzfuyBk9jaG7RDzGbGwa/Xp4alN+dXmB2z13aUdpMepqX7ztF/zCebYbtxqZyHIynApmH1v/6Q39PLYMcrtv9ZZAPWunO6cfaMeW+SZA0cpM8F3ISZix+IvjY5CUY/WQX9+duUpvtqHDmM49e5TGWttX7yujNza8UzuIvDIJB372TqRRgsmzDyRB2IvDY07Ryu3btQ126spg7Sr16SwvQFYN73a5CpUpCbnB95VS07wH/uE1e3FTDW5zkdaWxWoWQSmE6JgwMusRJxsVNu1tv05v66LMotb1ceT32oAKSMynI8mCmXbUPHU3htjAku4Dbvb2bq3ms4QtQiuHgZ9eQ7QllH+jgN9QdZzL2h4m1SqREGODd0Uqc4ql33h3WjW3RzlgUqqXM2TvO4GMUs="
  twilioTokenGibberish: "AgA8azzrHmHT60+oPonrTkm6eeZVNtjfoK8JgldYjNmVenlDM3aVTJAe44PGih1cH+Q18CjhbbgS0dk+LFr05c+Kbdraq6MFUlOhno7rtrNjib0s3/ngvPy3VFfwqmrnPKZ/6Ba0/SU5zKUYXDftr+d3surOq9pgWfcQWZACq2mtixBv5UwxS4k/9InPBjNAneS/MhoA7BLBS7R5O6wlGWEYvqiF5qUDOiAdaSdpuao7bMf0zXBvTIcpGGtf9yIv6nNb1ol4z+zERsbGpzbBQC9exb/UJkk7e3PHrFa9gcujge3nGdhpYHtYeL9q04P77tqqJz+zs6bckASpGv0+9NiZJMPwsUcSi4dR75+Ol7l6dtWIdQmahktAKFsp9BuSv3WkvZRLP6aqsGJGWyzNIlIknTdHhDROCu1DyedRqC9BnNt9uvIdfZ+ZwK65pI8r1b4m4hXNVMphSdVUcxnxiej7FvPIjO0ig12oiJMvXVIi+N46yhn1+2Oi6ZzZRDs7tZS8XFlttuny94nRO56iFcbydsTvfiZGEswGG6Ai4HeGHatUNUrX62lIP2dcn4FkVLSeeCSR9o2VT63bj/xxoGqE8oyYXbUkijEkwyZkvP+yDZvI0/3qCv9Esi4o07b/IWPZbA2PmnTycxeo/YbsZ6lfo7Bzz2bgZ4gLZVlYjxYq01y5MO3f8NNDgyCALSosWS150pOkk2mWWo0teFdRNquGY024z+ZLmqZTn6kqJC5rXg=="
  twilioPhoneGibberish: "AgA935Y0BGXd7Px68eKpDCbFuudubfOYnLmDAbwSwZ6chhpqOPFf2gn+NiXfVfq1CmGH2hxOiVHoRXCmeYTkmXo0CxOQnz5Jdkx6HW8sKP5PSzo1TaCHow2KGslbRjHlZvHOwYv6NE81wIfGHHsgi+qlPVhXMGwA0K1X/dGoHxypWW4aJQIGGX/K2xnhadCQkIf2WBVkrKmqTDwFk1+2/mOwlweWw9loofA44Sxwe8L9bzcIXqKJjHsjfB3W1omuzL1CWqWKif6G/T9WUbqwfENoOm21rY9fiLvWlhwMzp0FMJMDQLWt/j8Yz4HBh3I8j2Yl4l5GbGWq3UlHtMnkQSclRk9N9rYN4t26jFZT9gMweLSLiGXNSYoK9vcaSfBBzx1/XtHWsRIwba4OqALxJGLkyQ5ldyw9Pbl0VOgjsst/BxN/gYsUNvvlKohmmA5u+1H31wiupAjKlMXZX6sPKEQNRuCJx9BZPQWGwZ7np3yckmldxD2dbm/eSgOJePaU9hOAYmQv9qbNTE5ea8DE2/uK6OItB3bO9SowA//rzyicpH3h5x7kxOmUf6OY1YgzZnjnWRCSNGiPZwMFXq5zrt7OB1zRvKVb75drpelBvmbYLgF902eUVY4Brnfs/HXDdw3phBBRsTxCMpDJJh/t8ApH6tbeBQm2RwyhlVp8NXjpKnefvexJcLcUENXwbNAzZTNA/KiREnISxcks9Q=="
  mongoUrl: "mongodb://mongodb:27017"
  smtpServer: "smtp.gmail.com"
  smtpPort: "587"

livenessProbe:
  path: /docs
  port: 8000
  initialDelaySeconds: 15
  periodSeconds: 20
