apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-mongodb
  namespace: argocd
  labels:
    env: prod
    service: mongodb
spec:
  project: default
  source:
    repoURL: https://github.com/WashifyApp/mongodb.git
    targetRevision: main
    path: helm
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/WashifyApp/washify-gitops/main/prod/apps/mongodb/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: washify-prod-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
