apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
data:
  MONGO_URL: {{ if .Values.config }}{{ .Values.config.mongoUrl | quote }}{{ else }}"mongodb://mongodb:27017"{{ end }}
