apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/WashifyApp/washify-gitops.git'
    targetRevision: main
    path: charts/frontend
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev-env
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
