replicaCount: 1
namespace: dev-ns

image:
  repository: mongo
  tag: "6.0"

service:
  port: 27017

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

storage:
  className: nfs-csi
  size: 5Gi
  server: 10.0.0.100
  path: /exports/dev
