apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: {{ .Values.namespace }}
  name: frontend-deployment
  labels:
    app: frontend-service
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: BlueGreen
    blueGreen:
      activeService: {{ include "frontend.fullname" . }}
      previewService: {{ include "frontend.fullname" . }}-preview
      autoPromotionEnabled: false # Requires manual approval in ArgoCD
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          
