apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secret.jwtSecret | b64enc | quote }}
  SMTP_USER: {{ .Values.secret.smtpUser | b64enc | quote }}
  SMTP_PASS: {{ .Values.secret.smtpPass | b64enc | quote }}
  TWILIO_ACCOUNT_SID: {{ .Values.secret.twilioSid | b64enc | quote }}
  TWILIO_AUTH_TOKEN: {{ .Values.secret.twilioToken | b64enc | quote }}
  TWILIO_PHONE_NUMBER: {{ .Values.secret.twilioPhone | b64enc | quote }}
