{{- if .Values.secret.jwtSecretGibberish }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    JWT_SECRET: {{ .Values.secret.jwtSecretGibberish | quote }}
    SMTP_USER: {{ .Values.secret.smtpUserGibberish | quote }}
    SMTP_PASS: {{ .Values.secret.smtpPassGibberish | quote }}
    TWILIO_SID: {{ .Values.secret.twilioSidGibberish | quote }}
    TWILIO_TOKEN: {{ .Values.secret.twilioTokenGibberish | quote }}
    TWILIO_PHONE: {{ .Values.secret.twilioPhone | toString | b64enc | quote }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secret.jwtSecret | toString | b64enc | quote }}
  SMTP_USER: {{ .Values.secret.smtpUser | toString | b64enc | quote }}
  SMTP_PASS: {{ .Values.secret.smtpPass | toString | b64enc | quote }}
  TWILIO_SID: {{ .Values.secret.twilioSid | toString | b64enc | quote }}
  TWILIO_TOKEN: {{ .Values.secret.twilioToken | toString | b64enc | quote }}
  TWILIO_PHONE: {{ .Values.secret.twilioPhone | toString | b64enc | quote }}
{{- end }}
