apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
data:
  MONGO_URL: {{ .Values.config.mongoUrl | default "mongodb://mongodb:27017" | quote }}
  NOTIFICATION_URL: {{ .Values.config.notificationUrl | default "http://notification-service:8000" | quote }}
