replicaCount: 3
namespace: prod-ns

image:
  repository: aravindroy1/washify-review
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization: 80

configMap:
  name: review-config

secret:
  name: review-secret
  jwtSecretGibberish: "AgBD4axCqRvQuyFR5K09MTUGhJP4NYVt/pNud/Lw3pNIQQ/l+QhtHTgtOTvkkngZYFJavuplZ1TbREJhNZv4DXP0eMfNsoWYNdo/kHWt0g9cWvfcxvjxjzweAA4uWCvkLsA+Tm6+d1fov34kcdmN1dO4340l/NEM356+7y0oiF7Znd7oIWWC0v/LUfxaVjO6/XSWwvl/nK0TefFnkPiitd65JhQbSnV4+GtZJSZnauiwaVDhrf8U10G4yocJgjXhmIpF3Bc+EhI0wqWFf9BAKL8mux6KislsJBRAbnUwW7OZDPibDXZ8cOcc0zbq3QNQYIJV5cVVGnq42yMNjRBXNao40LM7RvQEb/09t2V7QsgsLxVPnaXJUO2WfBqohEqaMZtPAvMVSFxt1OYNjGHGhcfaACbjKAWI1OV2Juq2osJRY528TIeuwJ4tbghuKZMpvX+yb3nEc8+sm2aKPfoXaSJd9ClIp4C281krDJNCeJf1XS31wO3Fv2N4TQjRgbX0rYLJ9cA7ox3m/ADvMTZiFwXAWCiIZSDjr128Aw5+206h90ZMORY3y0MIS7CQHwSKH8WLacLi41u75QhHnwWyOlL8ucsOVDBvcyfl5vu1z0RQBmzR9KEYv0jDP1ck8uusXEQptbuXkuUgG5Y+HWFYNr4JnFkFLbGnunlPvmpT6+IRj05RJhc7QEhk6a7hrZs2J/6Qe7DUjlulT2iXG+9Q/FM="

config:
  mongoUrl: "mongodb://mongodb:27017"

livenessProbe:
  path: /docs
  port: 8000
  initialDelaySeconds: 10
  periodSeconds: 15
