# Global values for ALL services in DEV
global:
  environment: dev
  domain: dev.washify.app
  registry: ghcr.io/washifyapp
  replicaCount: 1

# Default resources for dev (cost saving)
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
