# Global values for ALL services in PROD
global:
  environment: prod
  domain: washify.app
  registry: ghcr.io/washifyapp
  replicaCount: 3

# Higher resources for prod (performance)
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
