apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: washify-root-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/WashifyApp/washify-gitops.git'
    targetRevision: main
    path: environments/dev/apps    # Watches this folder for new apps
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
